name: ants_clock
description: Ants clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 1.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/ant_frame_1.png
    - assets/ant_frame_2.png
    - assets/bg_foggy.png
    - assets/bg_rainy.png
    - assets/bg_snowy.png
    - assets/bg_sunny.png
    - assets/bg_thunderstorm.png
    - assets/bg_windy.png
    - assets/leaf_top_1.png
    - assets/leaf_top_2.png
    - assets/leaf_top_3.png
    - assets/leaf_top_4.png
    - assets/leaf_top_5.png
    - assets/leaf_right_1.png
    - assets/leaf_right_2.png
    - assets/leaf_right_3.png
    - assets/leaf_bottom_1.png
    - assets/leaf_bottom_2.png
    - assets/leaf_bottom_3.png
    - assets/leaf_bottom_4.png
    - assets/leaf_bottom_5.png
    - assets/leaf_left_1.png
    - assets/leaf_left_2.png
    - assets/leaf_anywhere_1.png